FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential && rm -rf /var/lib/apt/lists/*

COPY . .
RUN pip install --no-cache-dir .


EXPOSE 5055

CMD ["python", "run_api.py"]
